### ISSUE TITLE
Specifying radii in `Ellipsoid` (or diameter in `Sphere`)

### ISSUE THREAD

**Issue by wsshin** [stevengj/GeometryPrimitives.jl#10]
Currently, the `Ellipsoid` constructor takes the diameters `d`, whereas the `Sphere` constructor takes the radius `r`.

Because sphere is a special case of ellipsoid, to me it seems more consistent to change the `Ellipsoid` constructor to take the radii as well (or to change the `Sphere` constructor to take the diameter).

Can I create a PR on this, or it might be better to leave them as it is?

**Comment by stevengj** [comment]
Partly this is historical: in libctl (for Meep and MPB), an ellipsoid is a subtype of box and shares some code.  Even here, you basically specify an ellipsoid via the circumscribed box.

I guess I'm fine with changing spheres and cylinders to use the diameter instead of the radius.

**Comment by wsshin** [comment]
I was preparing PR for changing `r` to `d`, but then became worried about the future where we could have a concrete shape called `SectoralCylinder`, whose base is a [circular sector](https://en.wikipedia.org/wiki/Circular_sector).  (I had concrete shapes with all sorts of different base shapes in my previous project, and `SectoralCylinder` was one of them.)

For this `SectoralCylinder`, specifying the diameter would be a bit weird, because the base shape does not form a full circle.  Rather, it is usually a wedge shape, for which the radius is a more relevant size parameter.

This thought makes me feel that `r` might be a better constructor argument that could be applied to any circle-related shapes consistently, if we could slightly part with the legacy of libctl here...  What do you think?

**Comment by stevengj** [comment]
In libctl that shape is called "wedge"

**Comment by stevengj** [comment]
Changing ellipsoid to take semiaxes is fine with me, as long as there is a constructor that takes a Box
