### ISSUE TITLE
Concrete shapes inheriting from `Shape{N,D}` rather than `Shape{N}`

### ISSUE THREAD

**Issue by wsshin** [stevengj/GeometryPrimitives.jl#11]
Currently all the concrete shapes inherit from `Shape{N}`.  I hope them to inherit from `Shape{N,D}`, where `D` specifies the type of the `data` field of concrete shape types.  (This will require changing the definition of `Shape` to `abstract type Shape{N,D} end`.)

The reason for this change is as follows.  In my another module that uses `GeometryPrimitives`, I need to force all shapes to take an additional `SVector`, which can be conveniently stored in `data`.  Then, when I create an array of these shapes, I would want to type it `::Vector{Shape{N,SVector{N}}}`, which is only doable when all the concrete shapes inherit from `Shape{N,D}` rather than `Shape{N}`.

Because `Shape{N,D}` is a subtype of `Shape{N}`, all the concrete types will remain subtypes of `Shape{N}`.  Therefore, this change will not do much harm on existing code (e.g., functions taking `Shape{N}` can remain taking `Shape{N}`).

**Comment by stevengj** [comment]
Sure, sounds good.

**Comment by wsshin** [comment]
Created a PR: https://github.com/stevengj/GeometryPrimitives.jl/pull/12.

**Comment by wsshin** [comment]
It turns out that we also need to change 
```julia
mutable struct KDTree{K}
    s::Vector{Shape{K}}
    ...
end
```
to
```julia
mutable struct KDTree{K,S<:Shape{K}}
    s::Vector{S}
    ...
end
```
to fully resolve the issue discussed above.  

In the outside module that deals with shapes that always carry auxiliary data of type `D`, the shapes are always of type `Shape{N,D}` instead of less specific `Shape{N}`.  Therefore, `Shape{N,D}` is aliased to, e.g., `Object{N}` for convenience, and a vector of these shapes is defined as `Object{N}[obj₁, ..., objₙ]`.  When such a vector is passed to the current `KDTree` constructor to define the field `s`, type conversion from `Vector{Object{N}}` to `Vector{Shape{N}}` does not occur because the former is not a subtype of the latter.  The above described change will resolve this problem.

**Comment by stevengj** [comment]
Yes, you always want type fields to be a concrete type if possible.
