### ISSUE TITLE
Updating to Julia 0.7/1.0?

### ISSUE THREAD

**Issue by ianwilliamson** [stevengj/GeometryPrimitives.jl#31]
I was leveraging this useful little package for one of my codes which I'm now trying to update to support Julia 0.7/1.0.

Do you guys have any plans to update this to support Julia 0.7/1.0?

**Comment by wsshin** [comment]
Excited to know that there are users of this package other than two of us.  Yes, we surely have a plan to support Julia 0.7/1.0, towards the end of September.  Is that early enough for you?

**Comment by ianwilliamson** [comment]
Yeah... Ian from Shanhui's group. It has been pretty helpful for my FDFD.jl. No rush!
