### ISSUE TITLE
Convention for`findfirst()` return value

### ISSUE THREAD

**Issue by smartalecH** [stevengj/GeometryPrimitives.jl#38]
In order to be more consistent with the [definition](https://docs.julialang.org/en/v1/base/arrays/#Base.findfirst-Tuple{Any}) of `Base.findfirst()`, wouldn't it be better to return the _index_ of the shape, rather than the shape itself?

https://github.com/stevengj/GeometryPrimitives.jl/blob/7aeaa50b0b0108aa17cdc36c2209051c49181c42/src/util/kdtree.jl#L103-L111

**Comment by stevengj** [comment]
Yes, sounds good.

**Comment by stevengj** [comment]
Realize that this package was created in 2016, shortly after the release of Julia 0.5, so the `findfirst` API may have been different in those days.  

I don't think @wsshin has been using the kd-tree code, is that right Wonseok?

**Comment by wsshin** [comment]
@stevengj, that's right.  I don't use the k-d tree code for my FDFD stuffs, as I iterate over the vector of shapes, not over grid points.

Thanks for checking with me about potential issues before merging!
